5723dddb5e20
*** Log file does not exist: /opt/airflow/logs/dag_id=kafka_to_spark/run_id=scheduled__2025-06-15T02:00:00+00:00/task_id=produce_messages/attempt=1.log
*** Fetching from: http://5723dddb5e20:8793/log/dag_id=kafka_to_spark/run_id=scheduled__2025-06-15T02:00:00+00:00/task_id=produce_messages/attempt=1.log

[2025-06-15T03:00:13.811+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_spark.produce_messages scheduled__2025-06-15T02:00:00+00:00 [queued]>
[2025-06-15T03:00:13.815+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_spark.produce_messages scheduled__2025-06-15T02:00:00+00:00 [queued]>
[2025-06-15T03:00:13.815+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2025-06-15T03:00:13.815+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2025-06-15T03:00:13.815+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2025-06-15T03:00:13.822+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): produce_messages> on 2025-06-15 02:00:00+00:00
[2025-06-15T03:00:13.824+0000] {standard_task_runner.py:55} INFO - Started process 202 to run task
[2025-06-15T03:00:13.826+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_spark', 'produce_messages', 'scheduled__2025-06-15T02:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/kafka_spark_dag.py', '--cfg-path', '/tmp/tmp8e_cm0uu']
[2025-06-15T03:00:13.827+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask produce_messages
[2025-06-15T03:00:13.833+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-15T03:00:13.848+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-15T03:00:13.864+0000] {task_command.py:389} INFO - Running <TaskInstance: kafka_to_spark.produce_messages scheduled__2025-06-15T02:00:00+00:00 [running]> on host 5723dddb5e20
[2025-06-15T03:00:13.901+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=you
AIRFLOW_CTX_DAG_ID=kafka_to_spark
AIRFLOW_CTX_TASK_ID=produce_messages
AIRFLOW_CTX_EXECUTION_DATE=2025-06-15T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-06-15T02:00:00+00:00
[2025-06-15T03:00:13.902+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-15T03:00:13.902+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /producer/producer.py']
[2025-06-15T03:00:13.907+0000] {subprocess.py:86} INFO - Output:
[2025-06-15T03:00:13.951+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-15T03:00:13.952+0000] {subprocess.py:93} INFO -   File "/producer/producer.py", line 1, in <module>
[2025-06-15T03:00:13.952+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-06-15T03:00:13.952+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-06-15T03:00:13.953+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-15T03:00:13.958+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-15T03:00:13.960+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_spark, task_id=produce_messages, execution_date=20250615T020000, start_date=20250615T030013, end_date=20250615T030013
[2025-06-15T03:00:13.965+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 19 for task produce_messages (Bash command failed. The command returned a non-zero exit code 1.; 202)
[2025-06-15T03:00:13.997+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2025-06-15T03:00:14.015+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-15T03:01:38.299+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_spark.produce_messages scheduled__2025-06-15T02:00:00+00:00 [queued]>
[2025-06-15T03:01:38.303+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_spark.produce_messages scheduled__2025-06-15T02:00:00+00:00 [queued]>
[2025-06-15T03:01:38.303+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2025-06-15T03:01:38.303+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2025-06-15T03:01:38.303+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2025-06-15T03:01:38.309+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): produce_messages> on 2025-06-15 02:00:00+00:00
[2025-06-15T03:01:38.312+0000] {standard_task_runner.py:55} INFO - Started process 216 to run task
[2025-06-15T03:01:38.314+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_spark', 'produce_messages', 'scheduled__2025-06-15T02:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/kafka_spark_dag.py', '--cfg-path', '/tmp/tmpcud6j_6u']
[2025-06-15T03:01:38.315+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask produce_messages
[2025-06-15T03:01:38.324+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-15T03:01:38.336+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-15T03:01:38.353+0000] {task_command.py:389} INFO - Running <TaskInstance: kafka_to_spark.produce_messages scheduled__2025-06-15T02:00:00+00:00 [running]> on host 5723dddb5e20
[2025-06-15T03:01:38.390+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=you
AIRFLOW_CTX_DAG_ID=kafka_to_spark
AIRFLOW_CTX_TASK_ID=produce_messages
AIRFLOW_CTX_EXECUTION_DATE=2025-06-15T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-06-15T02:00:00+00:00
[2025-06-15T03:01:38.390+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-15T03:01:38.391+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /producer/producer.py']
[2025-06-15T03:01:38.398+0000] {subprocess.py:86} INFO - Output:
[2025-06-15T03:01:38.439+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-15T03:01:38.439+0000] {subprocess.py:93} INFO -   File "/producer/producer.py", line 1, in <module>
[2025-06-15T03:01:38.439+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-06-15T03:01:38.440+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-06-15T03:01:38.441+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-15T03:01:38.447+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-15T03:01:38.448+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_spark, task_id=produce_messages, execution_date=20250615T020000, start_date=20250615T030138, end_date=20250615T030138
[2025-06-15T03:01:38.454+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task produce_messages (Bash command failed. The command returned a non-zero exit code 1.; 216)
[2025-06-15T03:01:38.485+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2025-06-15T03:01:38.505+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check

